elasticsearch:
  build: ./elasticsearch
  volumes:
    - ./elasticsearch/config:/opt/elasticsearch/config
    - ./elasticsearch/data:/opt/elasticsearch/data
    - ./elasticsearch/log:/opt/elasticsearch/log
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  build: ./kibana
  volumes:
    - ./kibana/config:/opt/kibana/config-entry
  ports:
    - "5601:5601"
  links:
    - elasticsearch
